export enum BookGenre{
    FICTION = 'FICTION',
    DRAMA= 'DRAMA',
    FAIRYTALE = 'FAIRYTALE',
    FANTASY = 'FANTASY',
    FOLKLORE = 'FOLKLORE',
    MYSTERY = 'MYSTERY',
    BIOGRAPHY = 'BIOGRAPHY',
    HORROR = 'HORROR'

}